### PR TITLE
Added Storyboard/XIB compatibility

### PR DESCRIPTION
**Pull request by delannoyk**
- Made .style a readwrite property
- Implemented initWithCoder: (text is title, font is titleLabel.font, icon is image)

### CODE REVIEW

**Comment by chakming** [comment]
:+1:

**Comment by pronebird** [comment]
Merge it please!

**Comment by pronebird** [comment]
UP

**Comment by delannoyk** [comment]
@a1anyip Any way you could check this and eventually merge?

**Comment by samzhiwei** [comment]
UP

**Comment by joedaniels29** [comment]
+1

**Comment by a1anyip** [comment]
Thanks so much for the PR. As I just changed something and released 1.0.4, could you fix the conflicts, use tabs instead of 4 spaces, and rename `commonInit` to something like `_init`?

**Comment by delannoyk** [comment]
Hi @a1anyip 
I made everything you asked for.

**Comment by sirnacnud** [comment]
In 1.0.4, the super class of `AYVibrantButton` was changed to `UIControl`, so this PR now fails to compile.

**Pull request closed without merging**
